baseURL = "/"
title = "Electronic Lab Notebook"
theme = "temple"
# If not set, it will not appear. Otherwise it will show below your footer links
copyright = "(c) 2017 - 2018 -- All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Enables syntax highlighting
  highlight = true 
  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim", "sh", "R", "python"]
  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Your Name"
  github = "github"
  email = "your@email.com"
  gaid = "Your Google Analytics ID"
  twitter = "twitterID"
